[programs.localnet]
lock = "EVLUk8YzxevK24RRHEos5WxcXTqx8dDu79Xa4gGkQKMU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "testnet"
wallet = "config/solana/id.json"

[scripts]
test = "ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
